delete: unused files trial: fix error from build actions
error:
    ERROR: YOUR SITE COULD NOT BE BUILT:
    ------------------------------------
    Invalid YAML front matter in /github/workspace/src/main/items.md

refer to this commit:
https://github.com/LeinaGray/JAMstack-Practice/actions/runs/5629888439/job/15255346028